param(
    [string]$InputFile = "$env:USERPROFILE\Downloads\VehicleIDKI5.txt"
)

$RepoRoot = Split-Path $PSScriptRoot -Parent
$OutputPath = Join-Path $RepoRoot "Contents\mods\IKappaIDFadedRealWorldVehiclePhysics\42.18\media\lua\shared\IKFRVP_Profiles_KI5.lua"

$ValidVehicleId = [regex]::new('^[A-Za-z0-9][A-Za-z0-9_]*$')

function Test-ValidVehicleScriptId {
    param([string]$Name)
    if (-not $Name -or $Name.Length -lt 2) { return $false }
    if (-not $ValidVehicleId.IsMatch($Name)) { return $false }
    if ($Name -match '^(?i)https?') { return $false }
    if ($Name -match '^(?i)(collection|module)$') { return $false }
    return $true
}

function Read-VehicleIdsFromListFile {
    param([string]$Path)
    $ids = [System.Collections.Generic.HashSet[string]]::new()
    if (-not (Test-Path -LiteralPath $Path)) {
        throw "Vehicle list not found: $Path"
    }
    foreach ($line in [System.IO.File]::ReadLines($Path)) {
        $trimmed = $line.Trim()
        if ($trimmed -eq '' -or $trimmed.StartsWith('#')) { continue }
        foreach ($part in ($trimmed -split ',')) {
            $part = $part.Trim()
            if (-not $part) { continue }
            if ($part.StartsWith('Base.')) { $part = $part.Substring(5) }
            if (Test-ValidVehicleScriptId $part) {
                [void]$ids.Add($part)
            }
        }
    }
    return $ids
}

$ids = Read-VehicleIdsFromListFile -Path $InputFile
$sorted = $ids | Sort-Object

function Get-Profile($vid) {
    $vl = $vid.ToLower()
    if ($vl -match 'isocontainer') { return 'TrailerHeavy' }
    if ($vl -match 'trailer') {
        if ($vl -match 'livestock') { return 'TrailerHeavy' }
        if ($vl -match 'cargo|utility') {
            if ($vl -match 'large') { return 'TrailerHeavy' }
            return 'TrailerCargo'
        }
        return 'TrailerCargo'
    }
    if ($vl -match 'stepvan') { return 'StepVan' }
    if ($vid -match '^86fordE150|^63Type2Van') { return 'Van' }
    if ($vl -match 'caravan|^84merc') { return 'Van' }
    if ($vl -match 'ambulance') { return 'Van' }
    if ($vl -match 'm35a2|m49a2|m50a3|m62') { return 'Van' }
    if ($vl -match 'm998|m1008|m1009|m1010|m1028|m1031') { return 'SUV' }
    if ($vl -match 'swat') { return 'SUV' }
    if ($vl -match 'wrecker|flatbed') { return 'Pickup' }
    if ($vl -match 'gtr|lambo|countach|corvette|porsche911|firebird|camaro|cuda|barracuda|charger|roadrunner|gt500|mustanggt|svtcobra|regalgnx|regalturbot|lemans|gto|dodgert|dodgeta|dodgepd|falconxb|taurussho') { return 'Sport' }
    if ($vl -match 'impreza|lancerevo|mr2|240sx|bmwe30m3') { return 'CompactSport' }
    if ($vl -match 'mini|beetle|saturnsl2|saturnsseries') { return 'Compact' }
    if ($vl -match 'defender') {
        if ($vl -match 'utility') { return 'Pickup' }
        return 'Offroad'
    }
    if ($vl -match 'hilux|silverado|fordf150|fordf250|fordf350') { return 'Pickup' }
    if ($vl -match 'k5blazer') { return 'SUV' }
    if ($vl -match 'k10|k20|k30|k5') { return 'Pickup' }
    if ($vl -match 'suburban|jeepxj|jeepyj|touran|trooper') { return 'SUV' }
    if ($vl -match 'wagon' -and $vl -notmatch 'step') { return 'Wagon' }
    if ($vl -match 'cadillac|deville') { return 'Luxury' }
    if ($vl -match 'bmw') {
        if ($vl -match 'm3') { return 'Sport' }
        return 'Sedan'
    }
    if ($vl -match 'cvpi|fordcv[^p]|taurus|ltd|caprice|impala|volvo|delta88|lesabre|parisienne|falconps|mustangssp') { return 'Sedan' }
    return 'Sedan'
}

$groups = @{}
foreach ($vid in $sorted) {
    $p = Get-Profile $vid
    if (-not $groups.ContainsKey($p)) { $groups[$p] = [System.Collections.Generic.List[string]]::new() }
    $groups[$p].Add("Base.$vid")
}

$order = @('Compact','CompactSport','Sedan','ModernSedan','Wagon','Luxury','Sport','Offroad','Pickup','CrewPickup','SUV','Van','StepVan','TrailerLight','TrailerCargo','TrailerHeavy')
$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine("-- KI5 vehicle pack (autogenerated from VehicleIDKI5.txt)")
[void]$out.AppendLine("-- Total vehicles: $($sorted.Count)")
[void]$out.AppendLine("-- Plain global table: PZ Kahlua cannot compile UTF-8 BOM or top-level return here.")
[void]$out.AppendLine("IKFRVP_KI5_Roster = {")
$firstProfile = $true
foreach ($k in $order) {
    if (-not $groups.ContainsKey($k)) { continue }
    $names = $groups[$k] | Sort-Object
    if (-not $firstProfile) { [void]$out.AppendLine("") }
    $firstProfile = $false
    [void]$out.AppendLine("    $k = {")
    for ($i = 0; $i -lt $names.Count; $i += 4) {
        $chunk = $names[$i..([Math]::Min($i+3, $names.Count-1))]
        $line = '        ' + (($chunk | ForEach-Object { "`"$_`"" }) -join ', ')
        if ($i + 4 -lt $names.Count) { $line += ',' }
        [void]$out.AppendLine($line)
    }
    [void]$out.AppendLine('    },')
}
[void]$out.AppendLine("}")
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($OutputPath, $out.ToString(), $utf8NoBom)
Write-Output "Wrote $OutputPath"
Write-Output "Total: $($sorted.Count)"
$groups.Keys | Sort-Object | ForEach-Object { Write-Output "$_ : $($groups[$_].Count)" }
